version: '3.8'

services:
  # Servicio de la Base de Datos para Kong
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      - POSTGRES_USER=kong         # Usuario para la base de datos
      - POSTGRES_DB=kong           # Nombre de la base de datos
      - POSTGRES_PASSWORD=kongpass # Contraseña (solo para desarrollo local)
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio del API Gateway Kong
  kong:
    image: kong:3.4
    container_name: kong
    user: root # Necesario para algunas configuraciones iniciales
    environment:
      - KONG_DATABASE=postgres             # Le decimos a Kong que use PostgreSQL
      - KONG_PG_HOST=kong-db               # El host de la base de datos (el nombre del servicio de arriba)
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout  # Enviar logs a la salida estándar
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl # Puerto de administración
    depends_on:
      kong-db:
        condition: service_healthy # Kong no arrancará hasta que la BD esté lista
    ports:
      - "8000:8000" # Puerto para el tráfico HTTP de la API
      - "8443:8443" # Puerto para el tráfico HTTPS de la API
      - "8001:8001" # Puerto para la API de Administración de Kong
      - "8444:8444" # Puerto para la API de Administración de Kong (SSL)
